### ISSUE TITLE
closeServer errors with custom port

### ISSUE THREAD

**Issue by lilybelle** [micahblu/gulp-connect-php#13] opened 2015-06-02 03:47 UTC
If I use port 8000, the server starts and stops correctly, but if I use e.g. port 8080, the server starts fine but trying to stop it causes an error.

``` bash
exec error: Error: Command failed: 

/home/.../node_modules/gulp-connect-php/index.js:64
            var pid = stdout.match(/php\s+?([0-9]+)/)[1];
                                                     ^
TypeError: Cannot read property '1' of null
    at /home/.../node_modules/gulp-connect-php/index.js:64:48
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by micahblu** [comment] 2015-07-24 05:12
Could you please pull the latest and see if the issue is still present

**Comment by micahblu** [comment] 2015-10-28 21:41
I'm going to close this since it appears to have been an issue with an older version. Feel free to reopen if the problem persists

**Closed as completed by micahblu** 2015-10-28 21:41 UTC

**Comment by mikehuebner** [comment] 2015-12-14 09:14
I'm getting a similar error, its strange. Here is my task.

```
connect.server({
        keepalive: false,
        base: './build/',
        middleware: function(connect, opt) {
            return [
                modRewrite(['^[^\\.]*$ /index.html [L]']),
                compression()
            ];
        }
    }, () => {
        browserSync({
            port: 3030,
            proxy: 'localhost:8000',
            middleware: [
                hygienistMiddleware('build'),

                webpackDevMiddleware(bundler, {
                    // IMPORTANT: dev middleware can't access config, so we should
                    // provide publicPath by ourselves
                    publicPath: appConfig.output.publicPath,

                    // pretty colored output
                    stats: appConfig.stats,

                    // for other settings see
                    // http://webpack.github.io/docs/webpack-dev-middleware.html
                }),

                // bundler should be the same as above
                webpackHotMiddleware(bundler),
            ],

            // no need to watch '*.js' here, webpack will take care of it for us,
            // including full page reloads if HMR won't work
            files: [
                'build/public/**/*.css',
                'build/public/**/*.html',
                'build/content/**/*.*',
                'build/templates/**/*.*',
            ],
        });
    });
```

```
{ '0': 
   { [Error: Command failed: /bin/sh -c lsof -i :8000
   ]
     killed: false,
     code: 1,
     signal: null,
     cmd: '/bin/sh -c lsof -i :8000' },
  '1': '',
  '2': '' }
exec error: Error: Command failed: /bin/sh -c lsof -i :8000

/notmydirectory/notmyusername/connect.js:64
            var pid = stdout.match(/php\s+?([0-9]+)/)[1];
                                                     ^

TypeError: Cannot read property '1' of null
    at connect.js:65:58
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Curious as to what the params need to be for this to work.. I'm debugging it a bit now but wanted to bring this up again.
